DreamCrusher/Controllers/UserReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DreamCrusher.Models;
using DreamCrusher.Filter;

namespace DreamCrusher.Controllers
{
    public class UserReportsController : BaseController
    {
        public ActionResult UnPaidIncomes(Reports objreports)
        {
            List<Reports> lst = new List<Reports>();
            objreports.LoginId = Session["LoginId"].ToString();
            DataSet ds = objreports.GetUnPaidIncomes();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports obj = new Reports();
                    obj.FromLoginId = r["FromLoginId"].ToString();
                    obj.FromUserName = r["FromUserName"].ToString();
                    obj.Amount = r["Amount"].ToString();
                    obj.IncomeType = (r["IncomeType"].ToString());
                    obj.Date = (r["CurrentDate"].ToString());
                    lst.Add(obj);
                }
                objreports.lstunpaidincomes = lst;
            }
            return View(objreports);
        }
        public ActionResult PayoutReport()
        {
            Profile payoutDetail = new Profile();
            List<Profile> lst1 = new List<Profile>();

            payoutDetail.LoginId = Session["LoginID"].ToString();
            DataSet ds11 = payoutDetail.GetPayoutReport();

            if (ds11 != null && ds11.Tables.Count > 0 && ds11.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds11.Tables[0].Rows)
                {
                    Profile Obj = new Profile();
                    Obj.EncryptLoginID = Crypto.Encrypt(r["LoginId"].ToString());
                    Obj.EncryptPayoutNo = Crypto.Encrypt(r["PayoutNo"].ToString());

                    Obj.LoginId = r["LoginId"].ToString();
                    Obj.DisplayName = r["FirstName"].ToString();
                    Obj.PayoutNo = r["PayoutNo"].ToString();
                    Obj.ClosingDate = r["ClosingDate"].ToString();
                    Obj.BinaryIncome = r["BinaryIncome"].ToString();
                    Obj.DirectIncome=   r["DirectIncome"].ToString();
                    Obj.GrossAmount = r["GrossAmount"].ToString();
                    Obj.TDSAmount = r["TDSAmount"].ToString();
                    Obj.ProcessingFee = r["ProcessingFee"].ToString();
                    Obj.NetAmount = r["NetAmount"].ToString();
                    Obj.LeadershipBonus = r["DirectLeaderShipBonus"].ToString();
                    Obj.ProductWallet = r["ProductWallet"].ToString();
                    lst1.Add(Obj);
                }
                payoutDetail.lstPayoutDetail = lst1;
            }
            return View(payoutDetail);
        }
        [HttpPost]
        [ActionName("PayoutReport")]
        [OnAction(ButtonName = "Search")]
        public ActionResult PayoutReportBy()
        {
            Profile payoutDetail = new Profile();
            List<Profile> lst1 = new List<Profile>();
            payoutDetail.FromDate = string.IsNullOrEmpty(payoutDetail.FromDate) ? null : Common.ConvertToSystemDate(payoutDetail.FromDate, "dd/MM/yyyy");
            payoutDetail.ToDate = string.IsNullOrEmpty(payoutDetail.ToDate) ? null : Common.ConvertToSystemDate(payoutDetail.ToDate, "dd/MM/yyyy");
            payoutDetail.LoginId = Session["LoginID"].ToString();
            DataSet ds11 = payoutDetail.GetPayoutReport();

            if (ds11 != null && ds11.Tables.Count > 0 && ds11.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds11.Tables[0].Rows)
                {
                    Profile Obj = new Profile();
                    Obj.LoginId = r["LoginId"].ToString();
                    Obj.DisplayName = r["FirstName"].ToString();
                    Obj.PayoutNo = r["PayoutNo"].ToString();
                    Obj.ClosingDate = r["ClosingDate"].ToString();
                    Obj.BinaryIncome = r["BinaryIncome"].ToString();
                    Obj.DirectIncome = r["DirectIncome"].ToString();
                    Obj.GrossAmount = r["GrossAmount"].ToString();
                    Obj.TDSAmount = r["TDSAmount"].ToString();
                    Obj.ProcessingFee = r["ProcessingFee"].ToString();
                    Obj.NetAmount = r["NetAmount"].ToString();
                    Obj.LeadershipBonus = r["DirectLeaderShipBonus"].ToString();
                    Obj.ProductWallet = r["ProductWallet"].ToString();
                    lst1.Add(Obj);
                }
                payoutDetail.lstPayoutDetail = lst1;
            }
            return View(payoutDetail);
        }
        #region BoosterLedger

        public ActionResult BoosterLedger()
        {
            #region loadBoosterLedger
            List<Reports> lstVoucher = new List<Reports>();
            Reports model = new Reports();

            model.Fk_UserId = Session["Pk_userId"].ToString();
            DataSet ds = model.GetBoosterLedger();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports objUser = new Reports();
                    objUser.FK_InvestmentID = Crypto.Encrypt(r["PK_PaidBoosterID"].ToString());
                    objUser.MaturityDate = r["MaturityDate"].ToString();
                    objUser.UpgradtionDate = r["PaymentDate"].ToString();
                    objUser.Amount = r["Amount"].ToString();
                    objUser.TDSAmount = r["TDS"].ToString();
                    objUser.GrossAmount = r["GrossAmount"].ToString();
                    objUser.ProcessingFee = r["ProcessingCharge"].ToString();
                    objUser.Status = r["Status"].ToString();

                    lstVoucher.Add(objUser);
                }
                model.lstVoucherLedger = lstVoucher;
            }

            #endregion

            return View(model);
        }

        #endregion
        #region BoosterAchiever
        public ActionResult BoosterAchiever()
        {
            Reports model = new Reports();
            List<Reports> lst1 = new List<Reports>();
            model.LoginId = Session["LoginId"].ToString();
            DataSet ds = model.GetBoosterAchieverForAssociate();
            ViewBag.TotalAmount = 0;
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Reports Obj = new Reports();
                    Obj.LoginId = r["LoginId"].ToString();
                    Obj.DisplayName = r["Name"].ToString();
                    Obj.AchievementDate = r["AchievementDate"].ToString();
                    Obj.PermanentDate = r["PermanentDate"].ToString();
                    Obj.Amount = r["Amount"].ToString();
                    Obj.CssClass = r["CssClass"].ToString();
                    ViewBag.TotalAmount = Convert.ToDecimal(ViewBag.TotalAmount) + Convert.ToDecimal(r["Amount"].ToString());
                    lst1.Add(Obj);
                }
                model.lsttopupreport = lst1;
            }
            return View(model);
        }
        #endregion
        public ActionResult PayoutReceipt(string lid, string pno)
        {
            Profile model = new Profile();
            try
            {
                model.LoginId = Crypto.Decrypt(lid);
                model.PayoutNo = Crypto.Decrypt(pno);
                ViewBag.CompanyName = SoftwareDetails.CompanyName;
                ViewBag.CompanyAddress = SoftwareDetails.CompanyAddress;
                ViewBag.Phone = SoftwareDetails.LandLine;
                ViewBag.Email = SoftwareDetails.EmailID;
                DataSet ds = model.GetPayoutReport();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    model.LoginId = ds.Tables[0].Rows[0]["LoginId"].ToString();
                    model.DisplayName = ds.Tables[0].Rows[0]["FirstName"].ToString();
                    model.PayoutNo = ds.Tables[0].Rows[0]["PayoutNo"].ToString();
                    model.ClosingDate = ds.Tables[0].Rows[0]["ClosingDate"].ToString();
                    model.BinaryIncome = ds.Tables[0].Rows[0]["BinaryIncome"].ToString();
                    model.DirectIncome = ds.Tables[0].Rows[0]["DirectIncome"].ToString();
                    model.GrossAmount = ds.Tables[0].Rows[0]["GrossAmount"].ToString();
                    model.TDSAmount = ds.Tables[0].Rows[0]["TDSAmount"].ToString();
                    model.ProcessingFee = ds.Tables[0].Rows[0]["ProcessingFee"].ToString();
                    model.NetAmount = ds.Tables[0].Rows[0]["NetAmount"].ToString();
                    model.LeadershipBonus = ds.Tables[0].Rows[0]["DirectLeaderShipBonus"].ToString();
                    model.ProductWallet = ds.Tables[0].Rows[0]["ProductWallet"].ToString();
                    model.FromDate = ds.Tables[1].Rows[0]["FromDate"].ToString();
                    model.ToDate = ds.Tables[1].Rows[0]["ToDate"].ToString();
                    ViewBag.Income = Convert.ToDecimal(model.BinaryIncome) + Convert.ToDecimal(model.DirectIncome) + Convert.ToDecimal(model.LeadershipBonus);
                    ViewBag.Deduction = Convert.ToDecimal(model.TDSAmount) + Convert.ToDecimal(model.ProcessingFee) + Convert.ToDecimal(model.ProductWallet);
                    ViewBag.NetIncome = Convert.ToDecimal(ViewBag.Income) - Convert.ToDecimal(ViewBag.Deduction);
                    ViewBag.TDSPercent = Convert.ToDecimal(model.TDSAmount) * 100 / Convert.ToDecimal(ViewBag.Income);
                    ViewBag.TDSPercent = ViewBag.TDSPercent + "%";
                }
            }
            catch (Exception ex)
            {
            }
            return View(model);
        }

DreamCrusher/Views/UserReports/BoosterLedger.cshtml
@model DreamCrusher.Models.Reports

@{
    ViewBag.Title = "BoosterLedger";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ViewProfile", "User", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{

    <span style="color:red"> @TempData["UpdateProfile"]</span>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    View Profile

                </div>
                <div class="panel-body">

                    <fieldset>
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="table-responsive m-t-10">
                                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No.</th>
                                                        <th>Maturity Date</th>
                                                        <th>Payment Date</th>
                                                        <th>Gross Amount</th>
                                                        <th>TDS</th>
                                                        <th>Processing Charge</th>
                                                        <th>Net Amount</th>
                                                        <th>Status</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @if (Model != null)
                                                    {
                                                        if (Model.lstVoucherLedger != null)
                                                        {
                                                            int i = 1;
                                                            foreach (var Item in Model.lstVoucherLedger)
                                                            {
                                                                <tr class="text-left">
                                                                    <td>
                                                                        @i
                                                                    </td>
                                                                    <td>@Item.MaturityDate</td>
                                                                    <td>@Item.UpgradtionDate</td>
                                                                    <td>@Item.GrossAmount</td>
                                                                    <td>@Item.TDSAmount</td>
                                                                    <td>@Item.ProcessingFee</td>
                                                                    <td>@Item.Amount</td>
                                                                    <td>@Item.Status</td>
                                                                </tr>
                                                                i++;
                                                            }

                                                        }
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>

}

DreamCrusher/Views/UserReports/BusinessReport.cshtml
@model DreamCrusher.Models.Reports

@{
    ViewBag.Title = "BusinessReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("BusinessReport", "UserReports", FormMethod.Post, new { @id = "form1" }))
{
    

    <div class="page-content">
        <div class="row">
            <div class="col-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h5 class="mb-0">Business Report</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label class="form-label">   From Date </label>
                                @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @placeholder = "From  Date", @readonly = "read" })
                            </div>
                            <div class="col-md-3 mb-3">
                                <label class="form-label"> To Date </label>
                                @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @placeholder = "To  Date", @readonly = "read" })
                            </div>
                            <div class="col-md-3 mb-3">
                                <label class="form-label">  Leg </label>
                                @Html.DropDownListFor(m => m.Leg, new SelectList(ViewBag.Leg, "Value", "Text"), new { @class = "form-control form-select" })
                            </div>
                            <div class="col-md-1 mb-3">
                                <label class="form-label d-block">  IsDownline </label>
                                @Html.CheckBoxFor(m => m.IsDownline, new { @class = "form-check-input" })
                                
                            </div>
                            <div class="col-md-2 mb-3">
                                <label class="form-label d-block">&nbsp;  </label>
                                <input class="btn btn-light px-3" type="submit" value="Get Details" name="GetDetails" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example2" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>LoginId</th>
                                        <th>Name</th>

                                        <th>Topup Date</th>
                                        <th style="text-align:right">Amount</th>
                                        <th style="text-align:right">BV</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstassociate != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstassociate)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>
                                                    <td>@Item.LoginId</td>
                                                    <td>@Item.DisplayName</td>

                                                    <td>@Item.ClosingDate</td>
                                                    <td style="text-align:right">@Item.NetAmount</td>
                                                    <td style="text-align:right">@Item.LeadershipBonus</td>
                                                </tr>
                                                i++;
                                            }

                                        }
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>Total</td>
                                        <td style="text-align:right"><b style="color:blue;text-align:right">@ViewBag.TotalNetAmount</b></td>
                                        <td style="text-align:right"> <b style="color:blue;text-align:right">@ViewBag.TotalBV</b></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



}



<script src="../../vendor/jquery/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">


            <script>


                $('#FromDate').datepicker({
                    dateFormat: 'dd/mm/yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });
                $('#ToDate').datepicker({
                    dateFormat: 'dd/mm/yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });
                function isNumberOrDecimal(evt) {
                    var charCode = (evt.which) ? evt.which : evt.keyCode;
                    if (charCode != 46 && charCode > 31
                      && (charCode < 48 || charCode > 57))
                        return false;

                    return true;
                }

            </script>

DreamCrusher/Views/UserReports/CourseView.cshtml
@model DreamCrusher.Models.Reports

@{
    ViewBag.Title = "CourseView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #videoBox .coursesImg {
        height: 154px;
        width: 100%;
    }

    #videoBox .courseLink {
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        line-clamp: 1;
        -webkit-box-orient: vertical;
    }
    .btn-light{
        margin-top:28px;
    }
</style>
@using (Html.BeginForm("CourseView", "UserReports", FormMethod.Post, new { @id = "form1" }))
{
<div class="page-content">
    <div class="row">
        <div class="col-12 col-lg-12 col-xl-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex align-items-center justify-content-between">
                        <h5 class="mb-0">My Courses</h5>
                        @*<button class="btn btn-light repeater-add-btn px-4">Add</button>*@
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-12 col-xl-12">
            <div class="card">
                <div class="card-body">
                    <div class="row g-3">
                        <div class="col-md-4">
                            <label class="form-label"> Package</label>
                            @Html.DropDownListFor(m => m.Packages, new SelectList(ViewBag.ddlProduct, "Value", "Text"), new { @class = "form-control form-select",@onchange= "return onProductChangetoCourse();" })
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Courses </label>
                            @Html.DropDownListFor(m => m.CourseID, new SelectList(ViewBag.ddlProductCourses, "Value", "Text"), new { @class = "form-control form-select" })
                        </div>
                        <div class="col-md-4 mb-3">
                            <input class="btn btn-light px-3" type="submit" value="Search" name="btnCourseSearch" id="btnCourseSearch" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        @if (Model != null)
        {
            if (Model.lstCourse != null)
            {
                int i = 1;
                foreach (var Item in Model.lstCourse)
                {
                    <div class="col-12 col-lg-12 col-xl-3">
                        <div class="card">
                            <div class="card-body" id="videoBox">
                                <h5 class="mb-3"> <i class="bx bx-book-reader"></i> @Item.CourseName</h5>
                                <img src="@Item.CourseImage" class="img-fluid rounded mb-3 coursesImg" />
                                <div type="button" class="btn btn-light mb-2 position-relative">
                                    <img src="https://cdn-icons-png.flaticon.com/512/1384/1384060.png" class="img-fluid w-25 position-absolute top-50 start-50 translate-middle" data-bs-toggle="modal" data-bs-target="#@Item.CourseID" />
                                    <iframe width="100%" height="100%" src="@Item.CourseLink" title="YouTube video player" frameborder="0"></iframe>
                                </div>
                                @*<ul class="list-group list-group-flush">
                                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <a href="@Item.CourseLink" class="text-white courseLink" target="_blank" >@Item.CourseLink</a>
                                        </li>
                                    </ul>*@
                                @* modal video *@
                                <div class="col">
                                    <!-- Modal -->
                                    <div class="modal fade" id="@Item.CourseID" tabindex="-1" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Wacth This Video</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <iframe width="100%" height="400px" src="@Item.CourseLink" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                                                </div>
                                                @*<div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                        <button type="button" class="btn btn-primary">Save changes</button>
                                                    </div>*@
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>
}

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>
    function onProductChangetoCourse() {
        $("#divload").css({ 'display': '' });
        var value = $('#Packages').val();
        debugger;
        $.ajax({
            url: "/UserReports/GetProductChangetoCourse",
            Type: "Get",
            DataType: "JSON",
            data: { Packages: value },
            success: function (data) {
                debugger;
                $("#divload").css({ 'display': 'none' });
                    $("#CourseID").html(""); // clear before appending new list
                    $("#CourseID").empty();
                    $("#CourseID").append(
                          $('<option></option>').val(0).html('Select Course'));
                    $.each(data.ddlProductCourses, function (index, Coursecount) {
                        $("#CourseID").append(
                              $('<option></option>').val(Coursecount.Value).html(Coursecount.Text));

                    });
            }

        });

    }
</script>

DreamCrusher/Views/UserReports/DCMIReport.cshtml
@model DreamCrusher.Models.Reports
@{
 ViewBag.Title = "DCMI Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@using (Html.BeginForm("DCMIReport", "UserReports", FormMethod.Post, new { @id = "form1" }))
{


    <div class="page-content">
        <div class="row">
            <div class="col-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h5 class="mb-0">DCMI Report</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example2" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Sr No.</th>
                                        <th>Login Id</th>
                                        <th>Name</th>
                                        @*<th>Password</th>*@
                                        <th hidden="hidden">Pk_DCMIId</th>
                                        <th>Month</th>
                                        <th>Total Matching</th>
                                        <th>DCMI Gross Income</th>
                                        <th>TDS</th>
                                        <th>Admin Charge</th>
                                        <th>DCMI Income</th>
                                        <th>Transaction Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.lstdcmireport != null)
                                        {
                                            int i = 1;
                                            foreach (var Item in Model.lstdcmireport)
                                            {
                                                <tr class="text-left">
                                                    <td>@i</td>

                                                    <td>@Item.LoginId</td>
                                                    <td>@Item.Name</td>
                                                    @*<td>@Item.Password</td>*@
                                                    <td hidden="hidden">@Item.Pk_DCMIId</td>
                                                    <td>@Item.Month</td>
                                                    <td>@Item.TotalMatching</td>
                                                    <td>@Item.DCMIGrossIncome</td>
                                                    <td>@Item.TDS</td>
                                                    <td>@Item.AdminCharge</td>
                                                    <td>@Item.DCMIIncome</td>
                                                    <td>@Item.TransactionDate</td>
                                                </tr>
                                                i++;
                                            }

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script src="../vendor/jquery/jquery.min.js"></script>

<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>

    $('#TransactionDate').datepicker({
        dateFormat: 'yy-mm-dd',
    });
</script>